name: Economic Calendar Bot

on:
  schedule:
    - cron: '30 21 * * *' # KST 06:30
    - cron: '30 13 * * *' # KST 22:30
  workflow_dispatch:

# 아래 환경 변수를 추가하여 Node.js 24 사용을 강제합니다.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install python-telegram-bot requests beautifulsoup4

      - name: Execute Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
